dist: trusty
sudo: required

language: generic

script: ./test-build.sh $NODE_VERSION

jobs:
  include:
    - stage: Test
      env:
        - TEST: Doc Toc Check
      language: node_js
      install: npm i -g doctoc
      script:
        - cp README.md README.md.tmp &&
          doctoc --title='## Table of Contents' --github README.md &&
          diff -q README.md README.md.tmp

    - stage: Test
      env:
        - TEST: Shell Check
      script: shellcheck *.sh
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - shellcheck

    - stage: Build
      services:
          - docker
      addons:
        apt:
          packages:
            - docker-ce
      env:
        - NODE_VERSION: '4'

    - stage: Build
      env:
        - NODE_VERSION: '6'

    - stage: Build
      env:
        - NODE_VERSION: '8'

    - stage: Build
      env:
        - NODE_VERSION: '9'

    - stage: Build
      env:
        - NODE_VERSION: 'chakracore/8'
