sudo: required

services:
    - docker

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script:
    - shellcheck *.sh
    - ./test-build.sh $NODE_VERSION

env:
    matrix :
        - NODE_VERSION: '4.8'
        - NODE_VERSION: '6.11'
        - NODE_VERSION: '8.1'
