dist: trusty
sudo: required

language: node_js
node_js:
    - lts/*

services:
    - docker

addons:
  apt:
    packages:
      - docker-ce

script: ./test-build.sh $NODE_VERSION

jobs:
  include:
    - stage: Doc TOC Check
      install: npm i -g doctoc
      script:
        - cp README.md README.md.tmp &&
          doctoc --title='## Table of Contents' --github README.md &&
          diff -q README.md README.md.tmp

    - stage: Shell Check
      script: shellcheck *.sh
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - shellcheck

    - stage: Build
      env:
        - NODE_VERSION: '4'

    - stage: Build
      env:
        - NODE_VERSION: '6'

    - stage: Build
      env:
        - NODE_VERSION: '8'

    - stage: Build
      env:
        - NODE_VERSION: '9'

    - stage: Build
      env:
        - NODE_VERSION: 'chakracore/8'
