name: 10 on alpine3.9

on:
  push:
    paths:
      - functions.sh
      - test-build.sh
      - test-image.bats
      - 10/alpine3.9/Dockerfile
  pull_request:
    paths:
      - functions.sh
      - test-build.sh
      - test-image.bats
      - 10/alpine3.9/Dockerfile

jobs:
  build:
    name: 10 on alpine3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install bats
      - run: ./test-build.sh 10 alpine3.9
