name: Check Markdown links

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install markdown-link-check
        run: npm i -g markdown-link-check
      - name: Run markdown-link-check on MD files
        run: find . -name "*.md" | xargs -n 1 markdown-link-check -q
